In [2]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
from pathlib import Path

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# Dossier contenant les fichiers CSV
DATA_DIR = Path("data")  # ou Path("data") selon l'emplacement du notebook

# Liste des fichiers CSV
csv_files = sorted(DATA_DIR.glob("*.csv"))

if not csv_files:
    raise FileNotFoundError(f"Aucun fichier CSV trouvé dans {DATA_DIR.resolve()}")

# Liste déroulante
file_selector = widgets.Dropdown(
    options=[(file.name, file) for file in csv_files],
    description="Fichier :",
    layout=widgets.Layout(width="500px")
)

output = widgets.Output()

def load_csv(file_path):
    with output:
        clear_output(wait=True)

        try:
            df = pd.read_csv(file_path)

            print(f"Fichier : {file_path.name}")
            print(f"Dimensions : {df.shape[0]:,} lignes × {df.shape[1]} colonnes")
            display(df.head(20))

        except Exception as error:
            print(f"Erreur lors de la lecture : {error}")

def on_file_change(change):
    if change["name"] == "value" and change["new"] is not None:
        load_csv(change["new"])

file_selector.observe(on_file_change)

display(file_selector, output)

# Affiche automatiquement le premier fichier
load_csv(csv_files[0])

Dropdown(description='Fichier :', layout=Layout(width='500px'), options=(('bloc5_benchmark_industriel_externe.…

Output()

# Imports

In [27]:
usines = pd.read_csv("data/bloc5_usines.csv")
production = pd.read_csv("data/bloc5_production_mensuelle.csv")
prix_ener = pd.read_csv("data/bloc5_prix_energie_marche.csv")
stock_pieces= pd.read_csv("data/bloc5_stock_pieces_detachees.csv")
qualitee = pd.read_csv("data/bloc5_qualite_mensuelle.csv")
maintenance = pd.read_csv("data/bloc5_maintenance_mensuelle.csv")
benchmark = pd.read_csv("data/bloc5_benchmark_industriel_externe.csv")
ventes = pd.read_csv("data/bloc5_ventes_contrats.csv")
produit = pd.read_csv("data/bloc5_produits.csv")
client = pd.read_csv("data/bloc5_clients_industriels.csv")

# Modification des types

In [37]:
usines["factory_id"] = usines["factory_id"].astype(str)
production["factory_id"] = production["factory_id"].astype(str)
stock_pieces["factory_id"] = stock_pieces["factory_id"].astype(str)
stock_pieces["part_id"] = stock_pieces["part_id"].astype(str)
qualitee["factory_id"] = qualitee["factory_id"].astype(str)
maintenance["factory_id"] = maintenance["factory_id"].astype(str)
ventes["client_id"] = ventes["client_id"].astype(str)
ventes["product_id"] = ventes["product_id"].astype(str)
produit["product_id"] = produit["product_id"].astype(str)
client["client_id"] = client["client_id"].astype(str)


production["month"] = pd.to_datetime(production["month"])
prix_ener["month"] = pd.to_datetime(prix_ener["month"])
qualitee["month"] = pd.to_datetime(qualitee["month"])
maintenance["month"]=pd.to_datetime(maintenance["month"])
ventes["month"]=pd.to_datetime(ventes["month"])

# Feature Engineering

In [ ]:
production["target_rate"] = production["production_cycles"] / production["target_cycles"]
production["energy_per_cycle_kwh"] = production["energy_consumption_kwh"] / production["production_cycles"]

maintenance["total_maintenance_count"] = (
        maintenance["preventive_maintenance_count"]
        + maintenance["corrective_maintenance_count"]
    )

maintenance["preventive_maintenance_ratio"] = maintenance["preventive_maintenance_count"] /maintenance["total_maintenance_count"]

maintenance["maintenance_cost_per_intervention"] =  maintenance["maintenance_cost_eur"] / maintenance["total_maintenance_count"]

,month,factory_id,production_cycles,target_cycles,avg_cycle_duration_sec,downtime_hours,oee,energy_consumption_kwh,target_rate
0,2025-01-01,1,9175,11308,210.18,90,0.829,51726,0.811372
1,2025-01-01,2,10029,13665,217.07,96,0.777,82523,0.733919
2,2025-01-01,3,12687,13450,226.14,123,0.793,83438,0.943271
3,2025-01-01,4,11813,10982,175.18,35,0.705,51425,1.075669
4,2025-01-01,5,11883,10047,232.03,112,0.793,65593,1.182741
5,2025-02-01,1,9922,11627,192.61,70,0.865,78658,0.853359
6,2025-02-01,2,13424,10312,225.62,36,0.808,64144,1.301784
7,2025-02-01,3,10556,11873,184.86,107,0.842,82842,0.889076
8,2025-02-01,4,10731,10101,234.35,72,0.764,72670,1.062370
9,2025-02-01,5,8942,11633,237.37,95,0.795,52631,0.768675
10,2025-03-01,1,11685,12074,231.18,135,0.818,77180,0.967782
11,2025-03-01,2,11461,13755,211.73,133,0.777,76404,0.833224
12,2025-03-01,3,12402,12121,231.36,98,0.732,53454,1.023183
13,2025-03-01,4,8600,13943,224.33,138,0.834,85783,0.616797
14,2025-03-01,5,11717,11925,184.97,138,0.733,52996,0.982558
15,2025-04-01,1,13333,12870,206.98,85,0.844,80758,1.035975
16,2025-04-01,2,10256,12292,203.15,64,0.806,87392,0.834364
17,2025-04-01,3,12311,12860,208.52,138,0.772,58273,0.957309
18,2025-04-01,4,10611,13407,193.83,29,0.714,84142,0.791452
19,2025-04-01,5,11953,13291,211.60,87,0.763,58096,0.899330
20,2025-05-01,1,10330,12837,208.99,90,0.856,77581,0.804705
21,2025-05-01,2,11757,12284,221.47,29,0.871,65752,0.957099
22,2025-05-01,3,11949,13755,231.83,81,0.839,78762,0.868702
23,2025-05-01,4,10320,11855,239.54,48,0.902,76401,0.870519
24,2025-05-01,5,8726,12656,193.65,88,0.765,57752,0.689475
25,2025-06-01,1,14323,13508,203.79,82,0.891,51040,1.060335
26,2025-06-01,2,8201,11848,215.64,132,0.699,58028,0.692184
27,2025-06-01,3,10230,10494,218.48,121,0.806,62598,0.974843
28,2025-06-01,4,13676,13103,219.48,44,0.681,88554,1.043730
29,2025-06-01,5,12976,12352,228.87,135,0.793,53838,1.050518
30,2025-07-01,1,12671,10913,208.11,41,0.900,78077,1.161092
31,2025-07-01,2,10581,10345,204.24,45,0.895,83406,1.022813
32,2025-07-01,3,10706,12079,203.84,128,0.714,57890,0.886332
33,2025-07-01,4,11280,10057,242.12,74,0.884,48366,1.121607
34,2025-07-01,5,11042,12647,199.74,123,0.897,46676,0.873092
35,2025-08-01,1,12381,11949,197.94,63,0.784,52954,1.036154
36,2025-08-01,2,12276,13886,207.66,104,0.865,55085,0.884056
37,2025-08-01,3,13043,12128,189.49,104,0.757,84204,1.075445
38,2025-08-01,4,10111,12779,224.76,95,0.772,57811,0.791220
39,2025-08-01,5,13502,13774,187.14,107,0.805,48158,0.980253
40,2025-09-01,1,11901,13555,227.83,49,0.791,89474,0.877979
41,2025-09-01,2,8367,10528,220.20,52,0.861,78872,0.794738
42,2025-09-01,3,9328,10656,221.29,48,0.770,72876,0.875375
43,2025-09-01,4,12566,11696,235.76,74,0.750,67548,1.074384
44,2025-09-01,5,9631,11079,207.47,124,0.867,63852,0.869302
45,2025-10-01,1,12031,10724,197.81,86,0.782,79553,1.121876
46,2025-10-01,2,12498,13263,194.17,37,0.875,60160,0.942321
47,2025-10-01,3,8240,13906,181.52,83,0.829,71738,0.592550
48,2025-10-01,4,12665,13208,233.35,133,0.834,46781,0.958889
49,2025-10-01,5,11083,13467,185.97,96,0.838,80283,0.822975
50,2025-11-01,1,9973,10449,218.45,60,0.808,82227,0.954445
51,2025-11-01,2,14188,10878,214.89,97,0.742,81420,1.304284
52,2025-11-01,3,9286,10415,229.71,37,0.900,56224,0.891599
53,2025-11-01,4,9068,12803,179.23,70,0.846,57156,0.708271
54,2025-11-01,5,13491,12580,182.44,65,0.744,49188,1.072417
55,2025-12-01,1,10584,13816,197.02,58,0.739,45909,0.766068
56,2025-12-01,2,11572,13549,237.86,124,0.739,46011,0.854085
57,2025-12-01,3,8669,10395,191.47,64,0.708,89946,0.833959
58,2025-12-01,4,12797,12361,244.17,134,0.761,74887,1.035272
59,2025-12-01,5,13174,12562,220.83,103,0.689,71489,1.048718

In [48]:
production

,month,factory_id,production_cycles,target_cycles,avg_cycle_duration_sec,downtime_hours,oee,energy_consumption_kwh,target_rate
0,2025-01-01,1,9175,11308,210.18,90,0.829,51726,0.811372
1,2025-01-01,2,10029,13665,217.07,96,0.777,82523,0.733919
2,2025-01-01,3,12687,13450,226.14,123,0.793,83438,0.943271
3,2025-01-01,4,11813,10982,175.18,35,0.705,51425,1.075669
4,2025-01-01,5,11883,10047,232.03,112,0.793,65593,1.182741
5,2025-02-01,1,9922,11627,192.61,70,0.865,78658,0.853359
6,2025-02-01,2,13424,10312,225.62,36,0.808,64144,1.301784
7,2025-02-01,3,10556,11873,184.86,107,0.842,82842,0.889076
8,2025-02-01,4,10731,10101,234.35,72,0.764,72670,1.062370
9,2025-02-01,5,8942,11633,237.37,95,0.795,52631,0.768675
10,2025-03-01,1,11685,12074,231.18,135,0.818,77180,0.967782
11,2025-03-01,2,11461,13755,211.73,133,0.777,76404,0.833224
12,2025-03-01,3,12402,12121,231.36,98,0.732,53454,1.023183
13,2025-03-01,4,8600,13943,224.33,138,0.834,85783,0.616797
14,2025-03-01,5,11717,11925,184.97,138,0.733,52996,0.982558
15,2025-04-01,1,13333,12870,206.98,85,0.844,80758,1.035975
16,2025-04-01,2,10256,12292,203.15,64,0.806,87392,0.834364
17,2025-04-01,3,12311,12860,208.52,138,0.772,58273,0.957309
18,2025-04-01,4,10611,13407,193.83,29,0.714,84142,0.791452
19,2025-04-01,5,11953,13291,211.60,87,0.763,58096,0.899330
20,2025-05-01,1,10330,12837,208.99,90,0.856,77581,0.804705
21,2025-05-01,2,11757,12284,221.47,29,0.871,65752,0.957099
22,2025-05-01,3,11949,13755,231.83,81,0.839,78762,0.868702
23,2025-05-01,4,10320,11855,239.54,48,0.902,76401,0.870519
24,2025-05-01,5,8726,12656,193.65,88,0.765,57752,0.689475
25,2025-06-01,1,14323,13508,203.79,82,0.891,51040,1.060335
26,2025-06-01,2,8201,11848,215.64,132,0.699,58028,0.692184
27,2025-06-01,3,10230,10494,218.48,121,0.806,62598,0.974843
28,2025-06-01,4,13676,13103,219.48,44,0.681,88554,1.043730
29,2025-06-01,5,12976,12352,228.87,135,0.793,53838,1.050518
30,2025-07-01,1,12671,10913,208.11,41,0.900,78077,1.161092
31,2025-07-01,2,10581,10345,204.24,45,0.895,83406,1.022813
32,2025-07-01,3,10706,12079,203.84,128,0.714,57890,0.886332
33,2025-07-01,4,11280,10057,242.12,74,0.884,48366,1.121607
34,2025-07-01,5,11042,12647,199.74,123,0.897,46676,0.873092
35,2025-08-01,1,12381,11949,197.94,63,0.784,52954,1.036154
36,2025-08-01,2,12276,13886,207.66,104,0.865,55085,0.884056
37,2025-08-01,3,13043,12128,189.49,104,0.757,84204,1.075445
38,2025-08-01,4,10111,12779,224.76,95,0.772,57811,0.791220
39,2025-08-01,5,13502,13774,187.14,107,0.805,48158,0.980253
40,2025-09-01,1,11901,13555,227.83,49,0.791,89474,0.877979
41,2025-09-01,2,8367,10528,220.20,52,0.861,78872,0.794738
42,2025-09-01,3,9328,10656,221.29,48,0.770,72876,0.875375
43,2025-09-01,4,12566,11696,235.76,74,0.750,67548,1.074384
44,2025-09-01,5,9631,11079,207.47,124,0.867,63852,0.869302
45,2025-10-01,1,12031,10724,197.81,86,0.782,79553,1.121876
46,2025-10-01,2,12498,13263,194.17,37,0.875,60160,0.942321
47,2025-10-01,3,8240,13906,181.52,83,0.829,71738,0.592550
48,2025-10-01,4,12665,13208,233.35,133,0.834,46781,0.958889
49,2025-10-01,5,11083,13467,185.97,96,0.838,80283,0.822975
50,2025-11-01,1,9973,10449,218.45,60,0.808,82227,0.954445
51,2025-11-01,2,14188,10878,214.89,97,0.742,81420,1.304284
52,2025-11-01,3,9286,10415,229.71,37,0.900,56224,0.891599
53,2025-11-01,4,9068,12803,179.23,70,0.846,57156,0.708271
54,2025-11-01,5,13491,12580,182.44,65,0.744,49188,1.072417
55,2025-12-01,1,10584,13816,197.02,58,0.739,45909,0.766068
56,2025-12-01,2,11572,13549,237.86,124,0.739,46011,0.854085
57,2025-12-01,3,8669,10395,191.47,64,0.708,89946,0.833959
58,2025-12-01,4,12797,12361,244.17,134,0.761,74887,1.035272
59,2025-12-01,5,13174,12562,220.83,103,0.689,71489,1.048718

0      5.637711
1      8.228438
2      6.576653
3      4.353255
4      5.519902
5      7.927636
6      4.778308
7      7.847859
8      6.771969
9      5.885820
10     6.605049
11     6.666434
12     4.310111
13     9.974767
14     4.523001
15     6.057001
16     8.521061
17     4.733409
18     7.929696
19     4.860370
20     7.510261
21     5.592583
22     6.591514
23     7.403198
24     6.618382
25     3.563499
26     7.075722
27     6.119062
28     6.475139
29     4.149044
30     6.161866
31     7.882620
32     5.407248
33     4.287766
34     4.227133
35     4.277037
36     4.487211
37     6.455877
38     5.717634
39     3.566731
40     7.518192
41     9.426557
42     7.812607
43     5.375458
44     6.629841
45     6.612335
46     4.813570
47     8.706068
48     3.693723
49     7.243797
50     8.244961
51     5.738652
52     6.054706
53     6.303044
54     3.645986
55     4.337585
56     3.976063
57    10.375591
58     5.851918
59     5.426522
Name: energy_per_cycle_kwh, dtype: float64